// Mock Data
import { Client, Message } from "./types";

export const mockClients: Client[] = [
	{
	id: "1",
	name: "Northgate Medical Group",
	email: "s.mitchell@northgatemedical.com",
	phone: "+1 (704) 555-0142",
	initials: "NM",
	invoice: "INV-2024-0847",
	amount: 24750,
	daysOverdue: 22,
  },
  {
	id: "2",
	name: "Pinebrook Solutions",
	email: "billing@pinebrook.com",
	phone: "+1 (704) 555-0199",
	initials: "PB",
	invoice: "INV-2024-0731",
	amount: 8200,
	daysOverdue: 8,
  },
  {
	id: "3",
	name: "Meridian Design Co.",
	email: "ap@meridiandesign.com",
	phone: "+1 (704) 555-0863",
	initials: "MD",
	invoice: "INV-2024-0612",
	amount: 3500,
	daysOverdue: 45,
  },
  {
	id: "4",
	name: "Vertex Analytics",
	email: "finance@vertex.com",
	phone: "+1 (704) 555-0901",
	initials: "VA",
	invoice: "INV-2024-0889",
	amount: 41500,
	daysOverdue: 73,
  },
];

export const mockMessages: Message[] = [
  // Client 1: Northgate Medical Group
  {
    id: "m101",
    clientId: "1",
    direction: "out",
    channel: "email",
    timestamp: "2026-06-24T09:14:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Action Required: Invoice INV-2024-0847 - $24,750.00 Past Due",
    body: "Dear Northgate Medical Group,\n\nThis is a formal reminder that Invoice INV-2024-0847 for $24,750.00 was due on June 2, 2026 and is now 22 days past due...",
    status: "delivered",
  },
  {
    id: "m102",
    clientId: "1",
    direction: "out",
    channel: "sms",
    timestamp: "2026-06-24T09:18:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    body: "Hi Northgate Medical — INV-2024-0847 ($24,750) is 22 days past due. Please arrange payment or call us to discuss options.",
    status: "delivered",
  },
  {
    id: "m103",
    clientId: "1",
    direction: "in",
    channel: "email",
    timestamp: "2026-06-25T11:42:00Z",
    sender: "Sarah Mitchell",
    senderType: "client",
    senderInitials: "SM",
    senderLabel: "Accounts Payable · Northgate Medical Group",
    subject: "Re: Action Required: Invoice INV-2024-0847",
    body: "Hi,\n\nI wanted to flag a question about line item 3 on the invoice: the consulting hours (40 hrs @ $220/hr = $8,800) seem higher than what was quoted in our SOW. Can you clarify?",
    intent: "dispute",
    isRead: false,
  },

  // Client 2: Pinebrook Solutions 
  {
    id: "m201",
    clientId: "2",
    direction: "out",
    channel: "sms",
    timestamp: "2026-07-13T08:30:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    body: "Notice: Invoice INV-2024-0731 ($8,200) for Pinebrook Solutions is 8 days overdue.",
    status: "delivered",
  },
  {
    id: "m202",
    clientId: "2",
    direction: "in",
    channel: "sms",
    timestamp: "2026-07-13T08:45:00Z",
    sender: "Pinebrook Billing",
    senderType: "client",
    senderInitials: "PB",
    senderLabel: "SMS Inbound Listener",
    body: "Payment scheduled for Friday via ACH. Thanks!",
    intent: "promise_to_pay",
    isRead: true,
  },
  {
    id: "m203",
    clientId: "2",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-13T09:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Payment Schedule Confirmation - INV-2024-0731",
    body: "Thank you for confirming. We have recorded your payment schedule for this coming Friday.",
    status: "delivered",
  },

  // Client 3: Meridian Design Co. 
  {
    id: "m301",
    clientId: "3",
    direction: "out",
    channel: "email",
    timestamp: "2026-06-06T10:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Invoice INV-2024-0612 Overdue Reminder",
    body: "Hi Meridian Design team,\n\nInvoice INV-2024-0612 ($3,500) is past due. Please process payment at your earliest convenience.",
    status: "delivered",
  },
  {
    id: "m302",
    clientId: "3",
    direction: "out",
    channel: "sms",
    timestamp: "2026-06-20T14:15:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    body: "Urgent: INV-2024-0612 ($3,500) is now 32 days overdue. Please update payment status.",
    status: "failed",
  },
  {
    id: "m303",
    clientId: "3",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-03T09:30:00Z",
    sender: "Hoang Anh",
    senderType: "human",
    senderInitials: "HA",
    senderLabel: "AR Specialist · Manual Escalation",
    subject: "Final Notice: Overdue Account INV-2024-0612",
    body: "Hello AP Team,\n\nWe haven't received a response regarding invoice INV-2024-0612. Please contact us to prevent account pause.",
    status: "sent",
  },

  // Client 4: Vertex Analytics
  {
    id: "m401",
    clientId: "4",
    direction: "out",
    channel: "email",
    timestamp: "2026-05-10T11:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Invoice INV-2024-0889 - Payment Request",
    body: "Dear Vertex Analytics,\n\nInvoice INV-2024-0889 ($41,500.00) is pending payment.",
    status: "delivered",
  },
  {
    id: "m402",
    clientId: "4",
    direction: "in",
    channel: "email",
    timestamp: "2026-05-12T15:20:00Z",
    sender: "Finance Team",
    senderType: "client",
    senderInitials: "VA",
    senderLabel: "Finance · Vertex Analytics",
    subject: "Re: Invoice INV-2024-0889 - Payment Request",
    body: "Could you please re-send the PDF invoice copy with bank transfer details included?",
    intent: "invoice_request",
    isRead: true,
  },
  {
    id: "m403",
    clientId: "4",
    direction: "in",
    channel: "email",
    timestamp: "2026-07-21T08:10:00Z",
    sender: "David Vance",
    senderType: "client",
    senderInitials: "DV",
    senderLabel: "VP Finance · Vertex Analytics",
    subject: "Re: Urgent Action Required: INV-2024-0889",
    body: "Hi, our finance VP is reviewing this urgent payment today. Will update as soon as approval goes through.",
    intent: "other",
    isRead: false,
  },
];