import { Client, Message } from "../../lib/communications/types";

// CLIENTS
export const mockClients: Client[] = [
  {
    id: "1",
    name: "Vertex Analytics",
    email: "finance@vertexanalytics.com",
    phone: "+1 (555) 019-2831",
    initials: "VA",
    invoice: "INV-2024-0889",
    amount: 41500,
    daysOverdue: 73,
  },
  {
    id: "2",
    name: "Blue Ridge Corp",
    email: "accounts@blueridge.com",
    phone: "+1 (555) 014-9923",
    initials: "BC",
    invoice: "INV-2024-0788",
    amount: 7400,
    daysOverdue: 62,
  },
  {
    id: "3",
    name: "Meridian Design Co.",
    email: "ap@meridiandesign.com",
    phone: "+1 (555) 018-8631",
    initials: "MD",
    invoice: "INV-2024-0612",
    amount: 3500,
    daysOverdue: 45,
  },
  {
    id: "4",
    name: "Harlow & Partners",
    email: "billing@harlowpartners.com",
    phone: "+1 (555) 012-3341",
    initials: "HP",
    invoice: "INV-2024-0556",
    amount: 12300,
    daysOverdue: 31,
  },
  {
    id: "5",
    name: "Northgate Medical Group",
    email: "s.mitchell@northgatemedical.com",
    phone: "+1 (555) 017-4420",
    initials: "NM",
    invoice: "INV-2024-0847",
    amount: 24750,
    daysOverdue: 22,
  },
  {
    id: "6",
    name: "Riviera Tech",
    email: "invoices@rivieratech.com",
    phone: "+1 (555) 016-5512",
    initials: "RT",
    invoice: "INV-2024-0677",
    amount: 18000,
    daysOverdue: 15,
  },
  {
    id: "7",
    name: "Pinebrook Solutions",
    email: "billing@pinebrook.com",
    phone: "+1 (555) 015-7789",
    initials: "PS",
    invoice: "INV-2024-0731",
    amount: 8200,
    daysOverdue: 8,
  },
  {
    id: "8",
    name: "Atlas Consulting",
    email: "payables@atlasconsulting.com",
    phone: "+1 (555) 013-9081",
    initials: "AC",
    invoice: "INV-2024-0823",
    amount: 14200,
    daysOverdue: 5,
  },
  {
    id: "9",
    name: "Coastal Dynamics",
    email: "accounting@coastaldynamics.com",
    phone: "+1 (555) 011-6672",
    initials: "CD",
    invoice: "INV-2024-0445",
    amount: 5800,
    daysOverdue: 3,
  },
  {
    id: "10",
    name: "Summit Foods Ltd",
    email: "finance@summitfoods.com",
    phone: "+1 (555) 010-4432",
    initials: "SF",
    invoice: "INV-2024-0301",
    amount: 9750,
    daysOverdue: 0,
  },
  {
    id: "11",
    name: "Pacific Ventures",
    email: "ap@pacificventures.com",
    phone: "+1 (555) 019-1100",
    initials: "PV",
    invoice: "INV-2024-0902",
    amount: 31500,
    daysOverdue: 0,
  },
  {
    id: "12",
    name: "Sterling Media",
    email: "billing@sterlingmedia.com",
    phone: "+1 (555) 018-2299",
    initials: "SM",
    invoice: "INV-2024-0934",
    amount: 22100,
    daysOverdue: 0,
  },
];

// MESSAGES
export const mockMessages: Message[] = [
  {
    id: "m101",
    clientId: "1",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-15T09:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Urgent Notice: Overdue Invoice INV-2024-0889 ($41,500.00)",
    body: "Dear Vertex Analytics Team,\n\nInvoice INV-2024-0889 for $41,500.00 is currently 67 days past due. Please process payment immediately to prevent further escalation.",
    status: "delivered",
  },
  {
    id: "m102",
    clientId: "1",
    direction: "in",
    channel: "email",
    timestamp: "2026-07-21T14:15:00Z",
    sender: "David Vance",
    senderType: "client",
    senderInitials: "DV",
    senderLabel: "VP Finance · Vertex Analytics",
    subject: "Re: Urgent Notice: Overdue Invoice INV-2024-0889",
    body: "Hi, our executive board is reviewing this outstanding balance today. Approval for partial payment should be completed by this afternoon.",
    intent: "other",
    isRead: true,
  },
  {
    id: "m103",
    clientId: "1",
    direction: "out",
    channel: "sms",
    timestamp: "2026-07-21T14:30:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    body: "Hi David, thanks for the update. We have logged the expected payment timeline for INV-2024-0889.",
    status: "delivered",
  },
  {
    id: "m104",
    clientId: "1",
    direction: "in",
    channel: "sms",
    timestamp: "2026-07-22T10:10:00Z",
    sender: "David Vance",
    senderType: "client",
    senderInitials: "DV",
    senderLabel: "VP Finance · Vertex Analytics",
    body: "Could you send us an updated PDF statement for our records as well?",
    intent: "invoice_request",
    isRead: false,
  },
  {
    id: "m501",
    clientId: "5",
    direction: "out",
    channel: "sms",
    timestamp: "2026-06-24T09:18:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    body: "Hi Northgate Medical — INV-2024-0847 ($24,750) is 22 days past due. Please arrange payment or call us to discuss options. Reply STOP to opt out.",
    status: "delivered",
  },
  {
    id: "m502",
    clientId: "5",
    direction: "in",
    channel: "email",
    timestamp: "2026-06-25T11:42:00Z",
    sender: "Sarah Mitchell",
    senderType: "client",
    senderInitials: "SM",
    senderLabel: "Accounts Payable · Northgate Medical Group",
    subject: "Re: Action Required: Invoice INV-2024-0847",
    body: "Hi,\n\nI wanted to flag a question about line item 3 on the invoice: the consulting hours (40 hrs @ $220/hr = $8,800) seem higher than what was quoted in our SOW (35 hrs). Can you clarify or send an amended invoice?",
    intent: "dispute",
    isRead: true,
  },
  {
    id: "m503",
    clientId: "5",
    direction: "out",
    channel: "email",
    timestamp: "2026-06-25T14:00:00Z",
    sender: "Alex Rivera",
    senderType: "human",
    senderInitials: "AR",
    senderLabel: "AR Specialist · Manual Follow-up",
    subject: "Re: Action Required: Invoice INV-2024-0847",
    body: "Hi Sarah,\n\nThanks for catching that. I am reviewing the signed SOW with our account team now and will send over an adjusted invoice shortly.",
    status: "sent",
  },
  {
    id: "m504",
    clientId: "5",
    direction: "in",
    channel: "email",
    timestamp: "2026-06-26T08:30:00Z",
    sender: "Sarah Mitchell",
    senderType: "client",
    senderInitials: "SM",
    senderLabel: "Accounts Payable · Northgate Medical Group",
    subject: "Re: Action Required: Invoice INV-2024-0847",
    body: "Perfect, thank you! Once received, we will schedule payment on the same day.",
    intent: "promise_to_pay",
    isRead: true,
  },
  {
    id: "m701",
    clientId: "7",
    direction: "out",
    channel: "sms",
    timestamp: "2026-07-20T14:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    body: "Reminder: Invoice INV-2024-0731 ($8,200.00) for Pinebrook Solutions is 8 days past due. Please reply with payment status.",
    status: "delivered",
  },
  {
    id: "m702",
    clientId: "7",
    direction: "in",
    channel: "sms",
    timestamp: "2026-07-20T14:25:00Z",
    sender: "Pinebrook Accounts",
    senderType: "client",
    senderInitials: "PS",
    senderLabel: "SMS Inbound Listener",
    body: "ACH payment has been scheduled for Friday morning. Thanks!",
    intent: "promise_to_pay",
    isRead: true,
  },
  {
    id: "m703",
    clientId: "7",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-20T14:30:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Payment Schedule Confirmation - INV-2024-0731",
    body: "Thank you for confirming. We have recorded your ACH payment schedule for Friday morning.",
    status: "delivered",
  },
  {
    id: "m201",
    clientId: "2",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-10T09:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Overdue Notice: INV-2024-0788",
    body: "Invoice INV-2024-0788 ($7,400.00) is 62 days past due.",
    status: "delivered",
  },
  {
    id: "m301",
    clientId: "3",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-18T11:00:00Z",
    sender: "Alex Rivera",
    senderType: "human",
    senderInitials: "AR",
    senderLabel: "AR Specialist · Escalations",
    subject: "Final Notice: INV-2024-0612 Overdue Notice",
    body: "Hello AP Team,\n\nInvoice INV-2024-0612 ($3,500.00) is now 45 days past due. Please confirm when we can expect payment.",
    status: "sent",
  },
  {
    id: "m401",
    clientId: "4",
    direction: "out",
    channel: "email",
    timestamp: "2026-07-19T10:00:00Z",
    sender: "AI Collections Agent",
    senderType: "AI",
    senderInitials: "AI",
    senderLabel: "Automated · InvoiceIQ",
    subject: "Payment Reminder: INV-2024-0556",
    body: "Invoice INV-2024-0556 ($12,300.00) is currently 31 days overdue.",
    status: "delivered",
  },
];