import { Client, ClientFormData } from '../../lib/clients/types'

export const initialClients: Client[] = [
	{
		id: 'cli_1',
		company: 'Acme Corporation',
		contact: 'John Doe',
		email: 'johndoe@acme.com',
		phone: '+1 (555) 019-2834',
		channel: 'email',
		tone: 'firm',
		paymentTerms: 'Net 30',
		notes: 'Prefers digital receipts. Late payment history in Q2.',
		status: 'active',
		createdAt: new Date('2026-01-15T08:00:00Z').toISOString(),
	},
	{
		id: 'cli_2',
		company: 'Nexus Technologies',
		contact: 'Sarah Jenkins',
		email: 's.jenkins@nexustech.io',
		phone: '+1 (555) 014-9921',
		channel: 'sms',
		tone: 'friendly',
		paymentTerms: 'Net 15',
		notes: 'Always pays on time via automated bank transfer.',
		status: 'active',
		createdAt: new Date('2026-02-01T10:30:00Z').toISOString(),
	},
	{
		id: 'cli_3',
		company: 'Apex Logistics',
		contact: 'Michael Chang',
		email: 'm.chang@apexlogistics.com',
		phone: '+1 (555) 018-3342',
		channel: 'phone',
		tone: 'professional',
		paymentTerms: 'Net 45',
		notes: 'Requires phone confirmation before processing high-value invoices.',
		status: 'active',
		createdAt: new Date('2026-02-20T14:15:00Z').toISOString(),
	},
	{
		id: 'cli_4',
		company: 'Global Media Group',
		contact: 'Elena Rostova',
		email: 'elena.r@globalmedia.net',
		phone: '+1 (555) 012-7788',
		channel: 'email',
		tone: 'professional',
		paymentTerms: 'Net 60',
		notes: 'Enterprise account. Accounts payable department handles billing.',
		status: 'active',
		createdAt: new Date('2026-03-10T09:00:00Z').toISOString(),
	},
	{
		id: 'cli_5',
		company: 'Vortex Dynamics',
		contact: 'David Miller',
		email: 'dmiller@vortextch.com',
		phone: '+1 (555) 017-4411',
		channel: 'sms',
		tone: 'firm',
		paymentTerms: 'Due on Receipt',
		notes: 'High urgency client. Send SMS reminders 2 days prior to due date.',
		status: 'active',
		createdAt: new Date('2026-04-05T16:45:00Z').toISOString(),
	},
]

export const emptyForm: ClientFormData = {
	company: '',
	contact: '',
	email: '',
	phone: '',
	paymentTerms: 'Net 30',
	channel: 'email',
	tone: 'professional',
	notes: '',
}